FROM apache/airflow:3.1.0-python3.10

USER airflow

# Install OpenTelemetry SDK and other packages
RUN pip install \
    opentelemetry-sdk \
    opentelemetry-api \
    opentelemetry-instrumentation \
    opentelemetry-exporter-otlp \
    opentelemetry-instrumentation-requests

