
services:
  java-tester:
    image: gradle:8.12.0-jdk17
    container_name: java-tester
    hostname: java-tester
    working_dir: /app/testing/partial-spans
    volumes:
      - ../otel-java-test:/app/testing/partial-spans/otel-java-test
      - ../../../opentelemetry-java:/app/opentelemetry-java
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://${OTEL_COLLECTOR_HOSTNAME}:4317"
    depends_on:
      - ${OTEL_COLLECTOR_HOSTNAME}

